### ISSUE TITLE
RESTful API

### ISSUE THREAD

**Issue by imflash217** [vikaskumar-vsk/ProjectSpeech#7]
Descriptions of RESTful API.

**Comment by viktapas** [comment]
What is REST (Representational State Transfer)?
* REST is simply a unique web service architecture that aim for better interaction b/w client(s) and server.
* REST follows many constraints aiming best, secure web service/ interactions. These are:

   1. `Stateless`: This simply means that the request that is send by the client (browser) to the server must contain all the info that is required to understand the request. 

   2. `Cache`: To make the user experience snappier the response of most requested request(s) are saved either (or) on both ends i.e; client and server. Cache is very useful in case of surge of same/ similar request(s) to server. Cache also free up the server and increases its stability, reliability, etc by removing the need of processing the similar/ same requests. It also improves latency. The only let down of cache is sometimes it may provide different response to a request compared to if the request is processed by the server.

   3. `Uniform interface`: ?????????????????????????????

   4. `Layered system`: Layered system is used in REST because it add restriction to the knowledge of the system to a single layer. Also the data processing is done in a hierarchy steps. This limits the knowledge to client about all the resources available in server side. The let down is that it add latency to the processing of data, reducing user-perceived performance.

   5. `Code-on-demand`: This is an optional constraint. REST allows client functionality to be extended by downloading and executing code  in the form of applets (or) scripts. This reduces the no. of features required to be pre-implemented. This constraint is useful when all systems within an organization/ intranet support 'code-on-demand'. But it is also possible that some system(s) may not support 'code-on-demand' i.e; blocking the download of codes form external source by firewall, etc. That is why this constraint is optional and is designed keeping in mind the client may (or) may NOT support 'code-on-demand'.

**Comment by vikaskumar-vsk** [comment]
1. Stateless: This simply means that the request that is send by the client (browser) to the server must contain all the info that is required to understand the request.

**Comment by viktapas** [comment]
**# Doubts**
@vinaykumar2491 

1.  I failed to understand the **_uniform interface_** REST constraint. Please help me understanding this constraint.

2. If a system/ client supports **_code-on-demand_**, how it is implemented and improves client functionality is blurry to my concepts. I wish to discuss over this constraint.

**Comment by viktapas** [comment]
@vinaykumar2491 
I now understand what is REST but I'm facing difficulties understanding few things which are:

1. REST data elements
   -    resource
   -    resource identifier
   -    representation
   -    resource metadata
   -    control data

 2. Connectors
   -    client
   -   server
   -    cache
   -    resolver
   -    tunnel

**Comment by viktapas** [comment]
Concluding all REST constraints give `code-on-demand-uniform-layered-cache-stateless-server`.

**Comment by viktapas** [comment]
REST data elements:

- `resource`---Anything like docs, media. Hypertext reference must fit within the definition of a resource.
- `resource identifier`---URL that links to the resource.
- `representation`---It is a sequence of bytes, plus representation metadata to describe those bytes. It is consists of data and metadata describing the data.
- `representation metadata`---Its the data describing the nature of the resource like media type, last modified date, etc.??????
- `resource metadata`---It contains the info about resource that is not specific to the supplied representation.??????
- `control data`---It defines the purpose of a message b/w  components, such as the action being requested or the meaning of a response.??????

**Comment by viktapas** [comment]
REST connectors:

- `client`---this connector initializes the request.
- `server`--- this connector listens to the connections and responds in order to supply access to its services.
- `cache`---determines the cache-ability of a response. Cache can be shareable and non-shared cache.
- `resolver`---???????
- `tunnel`---???????

**Comment by viktapas** [comment]
REST components:

- `origin server`---
- `gateway`---
- `proxy`---
- `user agent`---

@vinaykumar2491 very confused at these components. What are these, what they do, how they work?

**Comment by viktapas** [comment]
`GET`, `PUT`, `POST`, `PATCH`, `DELETE` are HTTP verbs using which while making requests enhances requests' clarity.

`GET`--- is used to read a specific resource (or) multiple resources by an identifier.
`PUT`---is used to update/ replace resource(s) by an identifier.
`PATCH`---is used to update/ modify resource(s) by an identifier.
`POST`---is used to create a new resource by an identifier.
`DELETE`---is used to erase/ delete a resource by an identifier.

**Comment by viktapas** [comment]
Some HTTP response codes to indicate status:

`200 OK`---used to indicate 'success'.
`201 CREATED`---used to indicate successful creation [via `POST` (or) `PUT`{can't we get this response status via `PATCH`?}]
..................................................updating.....

**Comment by viktapas** [comment]
`204 NO CONTENT`--- indicates success but nothing is in the response body, often used for `DELETE` and `PUT` operations. (Why not `PATCH` operation?)

`400 BAD REQUEST`--- general error when fulfilling the request would cause an invalid state. Domain validation errors, missing data, etc. are some examples.

`401 UNAUTHORISED`--- error code response for missing or invalid authentication token.

`403 FORBIDDEN`--- error code for when the user is not authorised to perform the operation or the resource is unavailable for some reasons (ex. time constraints, etc).

`404 NOT FOUND`---used when the requested resource is not found, whether it doesn't exist (or) if there was an 401 (or) 403 that, for security reasons, this service wants to mask.

`405 METHOD NOT ALLOWED`---used to indicate that the requested URL exists but the requested HTTP method is not applicable. for example, POST/ users/12345 where the API doesn't support creation of resources this way (with an provided ID).

`409 CONFLICT`---whenever a resource conflict would be caused by fulfilling the requests. Duplicate entries, such as trying to create two customers with the same information (or) deleting root objects when cascade-delete is not supported are a couple of examples.

`500 INTERNAL SERVER ERROR`---never return this internationally. The general catch-all error when the server-side thrown an exception. Use this only for errors and that the customer cannot address from their end.

**Comment by viktapas** [comment]
*Finished*

**Comment by viktapas** [comment]
* Some Android Studio library calls:
`import android.view.View;`
`import android.graphics.Color;`
`import android.widget.TextView;`
`import android.widget.Button;`

**Comment by viktapas** [comment]
`import android.widget.TextView;`
`import android.view.MotionEvent;`
`import android.view.GestureDetector;`
`import android.support.v4.view.GestureDetectorCompat;`
